worker_processes auto;

pid /tmp/nginx.pid;

events {
    worker_connections 1024;
}

http {

    log_format service_log 
        '$remote_addr - $remote_user [$time_local] '
        '"$request" $status $body_bytes_sent '
        '"$http_referer" "$http_user_agent" '
        'service=$service_name';

    map $uri $service_name {
        ~^/([^/]+)/  $1;
        default      unknown;
    }

    map $service_name $service_port {
        auth          8001;
        employees     8003;
        wallet        8004;
        recognition   8005;
        rewards       8006;
        org           8007;
        default       8001;
    }

    server {
        listen 8000;

        access_log /var/log/nginx/access.log service_log;

        location /health {
            return 200 'OK';
        }

        location ~ ^/([^/]+)/(.+)$ {

            rewrite ^/(.*)$ /v1/$1 break;

            proxy_pass http://localhost:$service_port;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}