# Global settings for non-root execution
pid /tmp/nginx.pid;

events {
    worker_connections 1024;
}

http {
    # Redirect temp folders to /tmp where appuser has permissions
    client_body_temp_path /tmp/client_temp;
    proxy_temp_path       /tmp/proxy_temp;
    fastcgi_temp_path     /tmp/fastcgi_temp;
    uwsgi_temp_path       /tmp/uwsgi_temp;
    scgi_temp_path        /tmp/scgi_temp;

    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        listen 8000;

        location /health {
            return 200 'OK';
        }

        # Service routing
        location /auth/ {
            proxy_pass http://localhost:8001/;
            proxy_set_header Host $host;
        }

        location /employees/ {
            proxy_pass http://localhost:8003/;
            proxy_set_header Host $host;
        }

        location /wallet/ {
            proxy_pass http://localhost:8004/;
            proxy_set_header Host $host;
        }

        location /recognition/ {
            proxy_pass http://localhost:8005/;
            proxy_set_header Host $host;
        }

        location /rewards/ {
            proxy_pass http://localhost:8006/;
            proxy_set_header Host $host;
        }

        location /organization/ {
            proxy_pass http://localhost:8007/;
            proxy_set_header Host $host;
        }
    }
}