[unix_http_server]
file=/tmp/supervisor.sock
chmod=0777

[supervisord]
nodaemon=true
logfile=/app/supervisord.log
pidfile=/tmp/supervisord.pid
# Global environment variables for Prisma
environment=PYTHONPATH="/app",PRISMA_PY_BINARIES_PATH="/app/prisma_binaries",PRISMA_HOME="/app/.prisma",XDG_CACHE_HOME="/app/.cache"

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock


[program:auth]
priority=1
environment=STARTUP_DELAY="0"
command=/app/venv/bin/gunicorn src.auth.main:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8001 --workers 1 --timeout 60 --graceful-timeout 30 --worker-tmp-dir /tmp
directory=/app
autostart=true
autorestart=true
startsecs=5
stderr_logfile=/app/auth.err.log
stdout_logfile=/app/auth.out.log


[program:employees]
priority=2
environment=STARTUP_DELAY="5"
command=/app/venv/bin/gunicorn src.employees.main:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8003 --workers 1 --timeout 60 --graceful-timeout 30 --worker-tmp-dir /tmp
directory=/app
autostart=true
autorestart=true
startsecs=5
stderr_logfile=/app/employees.err.log
stdout_logfile=/app/employees.out.log


[program:wallet]
priority=3
environment=STARTUP_DELAY="10"
command=/app/venv/bin/gunicorn src.wallet.main:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8004 --workers 1 --timeout 60 --graceful-timeout 30 --worker-tmp-dir /tmp
directory=/app
autostart=true
autorestart=true
startsecs=5
stderr_logfile=/app/wallet.err.log
stdout_logfile=/app/wallet.out.log


[program:recognition]
priority=4
environment=STARTUP_DELAY="15"
command=/app/venv/bin/gunicorn src.recognition.main:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8005 --workers 1 --timeout 60 --graceful-timeout 30 --worker-tmp-dir /tmp
directory=/app
autostart=true
autorestart=true
startsecs=5
stderr_logfile=/app/recognition.err.log
stdout_logfile=/app/recognition.out.log


[program:rewards]
priority=5
environment=STARTUP_DELAY="20"
command=/app/venv/bin/gunicorn src.rewards.main:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8006 --workers 1 --timeout 60 --graceful-timeout 30 --worker-tmp-dir /tmp
directory=/app
autostart=true
autorestart=true
startsecs=5
stderr_logfile=/app/rewards.err.log
stdout_logfile=/app/rewards.out.log


[program:organization]
priority=6
environment=STARTUP_DELAY="25"
command=/app/venv/bin/gunicorn src.organization.main:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8007 --workers 1 --timeout 60 --graceful-timeout 30 --worker-tmp-dir /tmp
directory=/app
autostart=true
autorestart=true
startsecs=5
stderr_logfile=/app/organization.err.log
stdout_logfile=/app/organization.out.log


[program:nginx]
priority=7
command=bash -c "sleep 30 && exec /usr/sbin/nginx -c /app/nginx.conf -g 'daemon off;'"
autostart=true
autorestart=true
startsecs=5
stderr_logfile=/app/nginx.err.log
stdout_logfile=/app/nginx.out.log