[supervisord]
nodaemon=true
# REMOVED user=root (Let Docker handle the user)
logfile=/app/supervisord.log
pidfile=/tmp/supervisord.pid

[program:auth]
command=/app/venv/bin/gunicorn src.auth.main:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8001 --workers 1
directory=/app
autostart=true
autorestart=true
stderr_logfile=/app/auth.err.log
stdout_logfile=/app/auth.out.log

[program:employees]
command=/app/venv/bin/gunicorn src.employees.main:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8003 --workers 1
directory=/app
autostart=true
autorestart=true
stderr_logfile=/app/employees.err.log
stdout_logfile=/app/employees.out.log

[program:wallet]
command=/app/venv/bin/gunicorn src.wallet.main:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8004 --workers 1
directory=/app
autostart=true
autorestart=true
stderr_logfile=/app/wallet.err.log
stdout_logfile=/app/wallet.out.log

[program:recognition]
command=/app/venv/bin/gunicorn src.recognition.main:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8005 --workers 1
directory=/app
autostart=true
autorestart=true
stderr_logfile=/app/recognition.err.log
stdout_logfile=/app/recognition.out.log

[program:rewards]
command=/app/venv/bin/gunicorn src.rewards.main:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8006 --workers 1
directory=/app
autostart=true
autorestart=true
stderr_logfile=/app/rewards.err.log
stdout_logfile=/app/rewards.out.log

[program:organization]
command=/app/venv/bin/gunicorn src.organization.main:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8007 --workers 1
directory=/app
autostart=true
autorestart=true
stderr_logfile=/app/organization.err.log
stdout_logfile=/app/organization.out.log

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/app/nginx_out.log
stderr_logfile=/app/nginx_err.log