[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:auth]
command=/app/venv/bin/gunicorn src.auth.main:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8001 --workers 1
directory=/app
autostart=true
autorestart=true
stderr_logfile=/var/log/auth.err.log
stdout_logfile=/var/log/auth.out.log

[program:employees]
command=/app/venv/bin/gunicorn src.employees.main:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8003 --workers 1
directory=/app
autostart=true
autorestart=true
stderr_logfile=/var/log/employees.err.log
stdout_logfile=/var/log/employees.out.log

[program:wallet]
command=/app/venv/bin/gunicorn src.wallet.main:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8004 --workers 1
directory=/app
autostart=true
autorestart=true
stderr_logfile=/var/log/wallet.err.log
stdout_logfile=/var/log/wallet.out.log

[program:recognition]
command=/app/venv/bin/gunicorn src.recognition.main:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8005 --workers 1
directory=/app
autostart=true
autorestart=true
stderr_logfile=/var/log/recognition.err.log
stdout_logfile=/var/log/recognition.out.log

[program:rewards]
command=/app/venv/bin/gunicorn src.rewards.main:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8006 --workers 1
directory=/app
autostart=true
autorestart=true
stderr_logfile=/var/log/rewards.err.log
stdout_logfile=/var/log/rewards.out.log

[program:organization]
command=/app/venv/bin/gunicorn src.organization.main:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8007 --workers 1
directory=/app
autostart=true
autorestart=true
stderr_logfile=/var/log/organization.err.log
stdout_logfile=/var/log/organization.out.log