apiVersion: apps/v1
kind: Deployment
metadata:
  name: rewards-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rewards-service
  template:
    metadata:
      labels:
        app: rewards-service
    spec:
      containers:
      - name: rewards-container
        image: mrmonster786/rnr-rewards:latest
        ports:
        - containerPort: 8006
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: rewards-service
spec:
  selector:
    app: rewards-service
  ports:
    - protocol: TCP
      port: 8006
      targetPort: 8006