apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: skooner-ingress
  namespace: default
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    # This joins your existing ALB group without changing other services
    alb.ingress.kubernetes.io/group.name: aabhar-group
    alb.ingress.kubernetes.io/healthcheck-path: /skooner/favicon.ico
    alb.ingress.kubernetes.io/healthcheck-port: '4654'
    alb.ingress.kubernetes.io/success-codes: '200'
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    
    # Custom health check JUST for Skooner
    alb.ingress.kubernetes.io/healthcheck-path: /skooner/
    alb.ingress.kubernetes.io/healthcheck-port: '4654'
    alb.ingress.kubernetes.io/success-codes: '200'
spec:
  ingressClassName: alb
  rules:
  - host: api.aabhar.top
    http:
      paths:
      - path: /skooner
        pathType: Prefix
        backend:
          service:
            name: skooner
            port:
              number: 4654